import bpy

def merge_vertex_groups(obj, group_names, new_group_name):
    # 创建一个新的顶点组
    new_group = obj.vertex_groups.new(name=new_group_name)

    # 遍历所有指定的顶点组
    for group_name in group_names:
        if group_name in obj.vertex_groups:
            group = obj.vertex_groups[group_name]
            # 遍历所有顶点
            for v in obj.data.vertices:
                for g in v.groups:
                    if g.group == group.index:
                        # 获取当前顶点在该组中的权重
                        weight = group.weight(v.index)
                        try:
                            # 将权重添加到新的顶点组中
                            new_group.add([v.index], weight, 'ADD')
                        except RuntimeError:
                            pass

# 获取当前选中的对象
obj = bpy.context.active_object

# 要合并的顶点组名称列表
group_names = [
    "head",
    "head eyebrow upper.R",
    "head eyebrow 1.R",
    "head eyebrow 2.R",
    "head eyebrow upper.L",
    "head eyebrow 1.L",
    "head eyebrow 2.L",
    "head cheekbones.R",
    "head orbicularis lower_2.R",
    "head orbicularis lower_2.L",
    "head cheekbones.L",
    "head eyeball.L",
    "head eyeball iris.L",
    "head eyeball.R",
    "head eyeball iris.R",
    "head eyefold 1.R",
    "head eyefold 2.R",
    "head eyelid upper root.R",
    "head eyelid upper 1.R",
    "head eyelid upper 2.R",
    "head eyelid lower root.R",
    "head eyelid lower 1.R",
    "head eyelid lower 2.R",
    "head eyecorner in.R",
    "had eyecorner out.L",
    "head tearbag 1.R",
    "head tearbag 2.R",
    "head eyecorner out.R",
    "head eyecorner out.L",
    "head eyecorner in.L",
    "head eyefold 2.L",
    "head eyefold 1.L",
    "head eyelid upper root.L",
    "head eyelid upper 2.L",
    "head eyelid upper 1.L",
    "head eyelid lower root.L",
    "head eyelid lower 2.L",
    "head eyelid lower 1.L",
    "head tearbag 1.L",
    "head tearbag 2.L",
    "head nose middle",
    "head nostril.L",
    "head nose tip",
    "head nostril.R",
    "head nose lower adj",
    "head tearbag.L",
    "head cheek in.L",
    "head tearbag.R",
    "head cheek in.R",
    "head eyebrow middle",
    "head eyefold middle.L",
    "head eyefold middle.R",
    "head fore adj 1.R",
    "head fore upper middle",
    "head eyebrow out.R",
    "head eyebrow out.L",
    "head eyebrow middle adj",
    "head zygomatic upper.R",
    "head orbicularis lower.R",
    "head zygomatic upper.L",
    "head orbicularis lower.L",
    "head temple.R",
    "head temple.L",
    "head ear.L",
    "head ear.R",
    "Hair2_head forehead.R",
    "Hair2_head forehead.L",
    "Hair2_head forehead",
    "head lip upper middle in",
    "head lip upper 2 out.L",
    "head lip corner out.L",
    "head lip upper 3 out.L",
    "head lip upper 2 in.L",
    "head lip upper 2 out.R",
    "head lip corner out.R",
    "head lip upper 3 out.R",
    "head lip upper 2 in.R",
    "head jaw",
    "head lip lower middle out",
    "head lip lower 2 out.L",
    "head lip lower 3 out.L",
    "head lip lower 1 in.L",
    "head lip lower 2 out.R",
    "head lip lower 1 in.R",
    "head lip lower 3 out.R",
    "BelowJaw",
    "head throat.001.L",
    "head throat.001.R",
    "JawClench.L",
    "head jaw side 2.L",
    "head chin",
    "head jaw side 2.R",
    "JawClench.R",
    "head chin middle",
    "head chin.L",
    "head chin.R",
    "head teeth lower",
    "head under jaw",
    "head tongue 1",
    "head tongue 2",
    "head tongue 3",
    "head teeth upper",
    "C_InsideLip",
    "head masseter.L",
    "head masseter.R",
    "head cheek mid.L",
    "head nasobial 2.L",
    "head cheek 2.L",
    "head nasobial 3.L",
    "head cheek 1.L",
    "head nasobial 2.R",
    "head cheek 1.R",
    "head nasobial 3.R",
    "head cheek 2.R",
    "head cheek mid.R",
    "head nasobial 1.L",
    "head nasobial 1.R",
    "head lip upper adj.L",
    "head lip upper adj.R",
    "Hair2_hair adj",
    "Hair2_hair ponytail adj",
    "Hair2_hair band middle",
    "Hair2_hair front 1a.L",
    "Hair2_hair front 1b.L",
    "Hair2_hair side 1a.L",
    "Hair2_hair side 1b.L",
    "Hair2_hair side 1c.L",
    "Hair2_hair side 1d.L",
    "Hair2_hair side 2a.L",
    "Hair2_hair side 2b.L",
    "Hair2_hair side 2c.L",
    "Hair2_hair side 3a.L",
    "Hair2_hair side 3b.L",
    "Hair2_hair side 3c.L",
    "Hair2_hair front 2a.L",
    "Hair2_hair front 2b.L",
    "Hair2_hair front 2c.L",
    "Hair2_hair front 1a.R",
    "Hair2_hair front 1b.R",
    "Hair2_hair front 2a.R",
    "Hair2_hair front 2b.R",
    "Hair2_hair front 2c.R",
    "Hair2_hair side 1a.R",
    "Hair2_hair side 1b.R",
    "Hair2_hair side 1c.R",
    "Hair2_hair side 1d.R",
    "Hair2_hair side 2a.R",
    "Hair2_hair side 2b.R",
    "Hair2_hair side 2c.R",
    "Hair2_hair side 3a.R",
    "Hair2_hair side 3b.R",
    "Hair2_hair side 3c.R",
    "Hair2_hair side adj .L",
    "Hair2_hair side adj .R",
    "Hair2_hair ponytail 01",
    "Hair2_hair ponytail 02",
    "Hair2_hair ponytail 03",
    "Hair2_hair ponytail 04",
    "Hair2_hair ponytail 05",
    "Hair2_head eyebrow_4.R",
    "Hair2_head eyebrow_4.L",
    "Hair2_head temple.R",
    "Hair2_head temple.L",
  

  
    "lowerJaw",
    "lNasolabialLower",
    "rNasolabialLower",
    "lNasolabialMouthCorner",
    "rNasolabialMouthCorner",
    "lLipCorner",
    "lLipLowerOuter",
    "lLipLowerInner",
    "LipLowerMiddle",
    "rLipLowerInner",
    "rLipLowerOuter",
    "rLipCorner",
    "LipBelow",
    "Chin",
    "lCheekLower",
    "rCheekLower",
    "BelowJaw",
    "lJawClench",
    "rJawClench",
    "rBrowInner",
    "rBrowMid",
    "rBrowOuter",
    "lBrowInner",
    "lBrowMid",
    "lBrowOuter",
    "CenterBrow",
    "MidNoseBridge",
    "lEyelidInner",
    "lEyelidUpper",
    "lEyelidUpperInner",
    "lEyelidUpperOuter",
    "lEyelidOuter",
    "lEyelidLower",
    "lEyelidLowerOuter",
    "lEyelidLowerInner",
    "rEyelidInner",
    "rEyelidUpper",
    "rEyelidUpperInner",
    "rEyelidUpperOuter",
    "rEyelidOuter",
    "rEyelidLower",
    "rEyelidLowerOuter",
    "rEyelidLowerInner",
    "lSquintInner",
    "lSquintOuter",
    "rSquintInner",
    "rSquintOuter",
    "lCheekUpper",
    "rCheekUpper",
    "Nose",
    "lNostril",
    "rNostril",
    "lLipBelowNose",
    "rLipBelowNose",
    "lLipNasolabialCrease",
    "rLipNasolabialCrease",
    "lNasolabialUpper",
    "rNasolabialUpper",
    "lNasolabialMiddle",
    "rNasolabialMiddle",
    "LipUpperMiddle",
    "lLipUpperOuter",
    "lLipUpperInner",
    "rLipUpperInner",
    "rLipUpperOuter",
    "lEar",
    "rEar",
    
    "HairRoot",
    "Ab-HairVFLL01",
    "Ab-HairVFLL02",
    "Ab-HairVFL01",
    "Ab-HairVFL02",
    "Ab-HairVFR01",
    "Ab-HairVFR02",
    "Ab-HairVFRR01",
    "Ab-HairVFRR02",
    
    "Bip001-Head",
    "Ab-TL-HairB01",
    "Ab-TL-HairB02",
    "Ab-TL-HairB03",
    "Ab-TL-HairB04",
    "Ab-TL-HairB05",
    "Ab-TL-HairB06",
    "Ab-TL-HairB07",
    "Ab-TL-HairB08",
    "Ab-TL-HairB09",
    
    "Point003",
    "AB_WP02_Gear02",
    "AB_WP02_Gear03",
    "AB_WP02_Gear04",
    "AB_WP02_Gear05",
    "AB_WP02_Gear06",
    "AB_WP02_Gear07",
    "AB_WP02_Gear08",
    "AB_WP02_Gear09",
    "AB_WP02_Body2",
    "AB_WP02_Body",
    "AB_WP02_Top",
    "AB_WP02_TopL",
    "AB_WP02_TopR",
    "AB_WP02_TopT",
    "AB_WP02_TopC",
    "AB_WP02_TopL2",
    "AB_WP02_TopR2",
    "AB_WP02_BodyWLK",
    "AB_WP02_BodyWLF",
    "AB_WP02_BodyWRK",
    "AB_WP02_BodyWRF",
    "AB_WP02_Panel01",
    "AB_WP02_Panel02",
    "AB_WP02_Panel03",
    "AB_WP02_Panel04",
    "AB_WP02_Panel05",
    "AB_WP02_Panel06",
    "AB_WP02_Panel07",
    "AB_WP02_Gear01",
    "AB_WP02_Main_UP",
    "AB_WP02_Main_Dn",
    "AB_WP02_Tap4",
    "AB_WP02_Grip",
    "AB_WP02_Grip_sub",
    "AB_WP02_Tap1",
    "AB_WP02_Tap2",
    "AB_WP02_Tap3",
    "AB_WP02_Tap3_sub",

#    "下面是另一种",

]

# 新顶点组的名称
new_group_name = "頭"

# 调用函数合并顶点组
merge_vertex_groups(obj, group_names, new_group_name)